package com.pfe.projectsmanagements.exceptions.Tach;

public class TachAlreadyAffectedException extends  RuntimeException{
    private final static long servialID = 2L ;
}
